version: "3.8"
services:
  mongodb:
    image: mongo
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass12345
    volumes:
      - ./mongodb-data:/data/db
    ports:
      - "27017:27017"
    restart: unless-stopped
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=pass12345
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin123
    depends_on:
      - mongodb
    ports:
      - "8081:8081"
    restart: unless-stopped
  userapi:
    build:
      context: ./userApi
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb://root:pass12345@mongodb:27017/?maxPoolSize=20&w=majority
      - PORT=8000
      - DATABASE=user
      - COLLECTION=user
    depends_on:
      - mongodb
  contentapi:
    build:
      context: ./contentApi
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    environment:
      - USERURL=http://userapi:8000
      - MONGO_URI=mongodb://root:pass12345@mongodb:27017/?maxPoolSize=20&w=majority
      - PORT=8001
      - DATABASE=content
      - COLLECTION=content
    depends_on:
      - mongodb
  client:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - userurl=http://localhost:8000
        - contenturl=http://localhost:8001
    ports:
        - "80:80"

